# 语言设置
language: "zh_CN"

# 更新检查设置
update-checker:
  # 是否启用更新检查
  enabled: true
  # 检查频率（天）
  check-interval-days: 1

# 保护设置
protection:
  # 是否默认启用物品丢弃保护
  default-enabled: true
  
  # 物品描边设置
  glow:
    # 是否为受保护的物品添加描边效果
    enabled: true
    # 描边颜色 (WHITE, AQUA, BLACK, BLUE, DARK_AQUA, DARK_BLUE, DARK_GRAY, 
    # DARK_GREEN, DARK_PURPLE, DARK_RED, GOLD, GRAY, GREEN, LIGHT_PURPLE, RED, YELLOW)
    color: "WHITE"
  
  # 可见性设置
  visibility:
    # 其他玩家是否能看到受保护的物品（需要安装 ProtocolLib 或 PacketEvents 插件）
    # 插件会优先使用 ProtocolLib，若未安装则尝试使用 PacketEvents
    visible-to-others: true
    
# 消息设置
messages:
  # 是否启用 MiniMessage 格式
  # MiniMessage 格式允许更丰富的文本样式，例如悬停文本、点击事件等
  # 详细语法请参考：https://docs.advntr.dev/minimessage/format.html
  use-minimessage: true
    
# 通知设置
notifications:
  # 是否在丢弃受保护物品时通知玩家
  notify-on-drop: true
  
# 调试模式
debug: false
