name: PostDrop
version: '${version}'
main: com.github.postyizhan.PostDrop
api-version: '1.13'
description: 'A plugin to protect dropped items from other players'
authors: [postyizhan]
softdepend: [ProtocolLib, packetevents, PlaceholderAPI]

commands:
  postdrop:
    description: Main command for PostDrop plugin
    aliases: [pd]
    usage: /<command> [help|reload|version|toggle|update|visibility]
    
permissions:
  postdrop.*:
    description: Gives access to all PostDrop commands
    default: op
    children:
      postdrop.reload: true
      postdrop.toggle: true
      postdrop.update: true
      postdrop.admin: true
  postdrop.reload:
    description: Allows players to reload the plugin
    default: op
  postdrop.toggle:
    description: Allows players to toggle item protection
    default: true
  postdrop.update:
    description: Allows players to check for updates
    default: op
  postdrop.admin:
    description: Allows players to use admin commands
    default: op
